### PR TITLE
Adding export command

### PR DESCRIPTION
**Pull request by nfischer**
This adds the `export` command ([man page](http://ss64.com/bash/export.html)) into the mix.

Similar to how `cash $ alias foo ls` succeeds (when it wouldn't succeed in bash), `cash $ export FOO $PATH` also succeeds in redefining `FOO` to be `$PATH`.

This exports to `process.env`, which is case insensitive on Windows (even for the new attributes I'm adding). So, on Windows, you can do things like:

```Bash
cash $ export FOO='hello'
cash $ echo $foo
hello
```

I don't think there's any good way to avoid this behavior, so until it's a problem, I suggest it be kept.

This doesn't replace regular assignment. In bash, you can do non-exported assignment of the form: `foo=bar`, creating a variable named foo with the value "bar". I couldn't figure out a way to write the syntax for regular assignment (posted issue #42 for this).

@dthree do you have any suggestions for additional tests? I modeled unit tests off the ones for `alias`.

### CODE REVIEW

**Comment by nfischer** [comment]
Also, the [contributing page](https://github.com/dthree/cash/wiki/Contributing) is pretty nicely done :+1:

**Comment by dthree** [comment]
Very nicely done!

I don't see anything wrong with this. :+1:

**Comment by dthree** [comment]
On a separate note, do we want to publish `export` as a global module? I don't see why not.

**Comment by nfischer** [comment]
Would it work as a separate module? Internally, it modifies `process.env`, which gets reset as soon as node exits. Not sure if it would work as its own standalone module.

I suppose it might be useful for `export` without arguments, since that prints out the contents of `process.env`.

**Comment by dthree** [comment]
Ah good point.

http://stackoverflow.com/questions/496702/can-a-shell-script-set-environment-variables-of-the-calling-shell

I was thinking that, if called independently, it could `export` to the current shell's environment. We'd have to find some tricky way to do that.

**Comment by nfischer** [comment]
I suspect that's not possible (at least on POSIX), since I think it's an operating system security feature. I don't know as much about Windows, however.

**Comment by dthree** [comment]
Okay, let's scratch it.

**Comment by nfischer** [comment]
I think it should be good (see https://github.com/dthree/cash/blob/master/commands.json#L26). Let me know if I should change something.

**Comment by dthree** [comment]
Oh, silly me, you'd already added it!

Perfect duplication of instructions, btw! Not a single thing wrong on that PR.

**Comment by nfischer** [comment]
> Perfect duplication of instructions, btw! Not a single thing wrong on that PR.

Woohoo! :+1:

**Pull request merged**
