### PR TITLE
New command: source

### PR DESCRIPTION
**Pull request by nfischer**
This adds [source](http://ss64.com/bash/source.html) as requested in the roadmap.

This executes any given cash script in the current environment, allowing it to modify variables, aliases, current directory, etc.

I also added in code to check for an initialization file, as requested in #20. This file is named `.cashrc` on Linux/unix systems (following the common convention), and is named `_cashrc` for Windows (this is consistent with how vim looks for `_vimrc`, `_gvimrc`, etc. This file must be located in the user's home folder.

I tried allowing this to be an external command, so deps and such should be double checked for that.

### CODE REVIEW

**Comment by dthree** [comment]
Nice!! Not around right now, but a little later today will do a full review. Didn't see anything off the bat, except AppVeyor is failing, and it looks like there's a tiny bit of missed coverage.

Will let you know back soon!

**Comment by nfischer** [comment]
Whoops. I see the issue with appveyor. The test case is invalid on windows (since ShellJS's `chmod()` doesn't work well on Windows). This has been a struggle for us to get quite right in the project.

I'll probably skip the test for Windows (it just checks that attempting to read from an unreadable file is an error). If I can find out how to make `chmod()` work better on ShellJS, we can add it back in once that's fixed.

**Comment by nfischer** [comment]
Also, I forgot to mention this earlier, but I also have an alias to `.`. So `source file.sh` is equivalent to `. file.sh`, as it is in Bash. This is documented in the help file.

Also, on second thought, it might be better to not expose `source` as a global install (since what makes `source` interesting is that it modifies the current environment) if we can instead allow `cash` to  execute scripts:

```
> cash myCashScript.sh # run this from Windows
hello world
... # all other output/side-effects from script
> # next windows command
```

**Comment by nfischer** [comment]
@dthree is there a way to ignore certain lines for coverage? I tried `/* instanbul ignore next */`, but that didn't quite seem to work. The lines I would be ignoring would be the init file lines (not sure how to test those without modifying the file system).

**Comment by nfischer** [comment]
Also, I updated this to remove source from the global install, since it probably shouldn't be exposed that way since it wouldn't quite have the right semantics. It requires the rest of the cash utilities to be installed anyway, since all it does is execute a script a script via cash.

Let me know if I should squash commits to wipe out the part where I had the global install stuff :+1:

**Comment by dthree** [comment]
K makes sense. Sorry, things going crazy right now. As soon as I get some time will pull this in.

**Comment by nfischer** [comment]
No hurry, as long as we get things right. No need to rush :+1:

**Comment by dthree** [comment]
@nfischer reviewed and looks great!

Can you please do a rebase real quick on this? I merged tail and there's some unrelated conflicts including the latest version of Vorpal. Right after this, I can merge.

**Comment by nfischer** [comment]
@dthree I think this should be fixed now. I suspect the coveralls will still be failing, since it doesn't seem to be skipping the right lines for coverage.

**Comment by dthree** [comment]
Awesome, thanks! (AppVeyor looks fine).

**Comment by dthree** [comment]
Cleaned up and released in `v0.8.0`.

https://github.com/dthree/cash/commit/963be43ddbaa18dba46ef5a101a62c2ee431cde0

Thanks so much @nfischer!

(btw, figured out the tests on loading `.cashrc`)

**Comment by nfischer** [comment]
> (btw, figured out the tests on loading .cashrc)

Awesome! Thanks!

**Pull request merged**
