### PR TITLE
Added the version update to 8 in the Travis and Appveyor configs

### PR DESCRIPTION
**Pull request by andreGarvin**
@dthree Check it out

### CODE REVIEW

**Comment by andreGarvin** [comment]
Hey, @RyanZim are you going to merge this PR ?

**Comment by RyanZim** [comment]
@andreGarvin I don't have merge rights here, I'm just a community member trying to help out and save the developers some time reviewing PRs.

**Comment by andreGarvin** [comment]
Oh okay, sorry about that @*RyanZim. I *hope did not seem very impatient. I
just thought it was weird sorry about that

**Comment by nfischer** [comment]
Thanks!

**Pull request merged**
