### PR TITLE
feat: add ability to run scripts, and add '-c' flag

### LINKED ISSUE #51: Add support for executing scripts
It'd be nice if cash supported the following sort of thing:

``` Bash
bash $ cash filename.sh # execute filename.sh, using cash, in a separate process, and return
hello world
... # all other script output from filename.sh
bash $ # it returns back to a regular prompt (bash, zsh, cmd.exe, whatever we started from)
```

### PR DESCRIPTION
**Pull request by nfischer**
Fixes #51 and #69 (since they were related).

Run commands with the `-c` option:

```
> cash -c 'echo hello world'
hello world
>
```

Run scripts like so:

```
> cash helloWorldScript.sh
Hello world!
```

Also, this adds in the beginning of local variables. This sets the `$0`, `$1`, etc. variables as local variables. These variables still aren't exposed to the user, but I can add that functionality in pretty easily by refactoring the preparser a little bit.

### CODE REVIEW

**Comment by nfischer** [comment]
Not sure if it's possible to write tests for these features (they work fine on my Linux box, of course).

I can add in the appropriate ignore comments later if there's no way to test.

**Comment by RyanZim** [comment]
Any movement on this?

**Comment by danielbayley** [comment]
> Any movement on this?

Wondering the same… what needs doing to get this over the line? Maybe I can help…

**Comment by nfischer** [comment]
@dthree can you review?

@danielbayley can you test this branch locally with npm's `script-shell` option?

@dthree see shelljs/shx#117. Cash might be a great solution for users who want to take advantage of the `script-shell` option in `npm`. It'll rock once we switch to `bash-parser`.

**Comment by dthree** [comment]
This is nice! I like :)

**Pull request merged**
