### PR TITLE
Update travis to test against Node v7

### PR DESCRIPTION
**Pull request by RichyHBM**

### CODE REVIEW

**Comment by RichyHBM** [comment]
PR for https://github.com/dthree/cash/issues/99, currently failing due to line endings in JS string yet tests run fine locally, may need to use Node's os.EOL rather than embedding a \n in the string?

**Comment by nfischer** [comment]
@RichyHBM please rebase this off of master

**Comment by RichyHBM** [comment]
All done!

**Comment by nfischer** [comment]
LGTM. Thanks @RichyHBM!

**Pull request merged**
