### PR TITLE
use the `username` module’s Promise API

### PR DESCRIPTION
**Pull request by addaleax**
Since version 2.0.0, the `username` module returns Promise instances rather than using callbacks.

### CODE REVIEW

**Comment by nfischer** [comment]
@addaleax Awesome! Would you be able to make this change to the file in `src/` instead, and then build this with `gulp`? Thanks!

**Comment by addaleax** [comment]
@nfischer Eh, sure… should I commit the updated changes in dist/, too?

**Comment by addaleax** [comment]
Updated this with changes only in src/ instead of dist/ :)

**Comment by nfischer** [comment]
@addaleax Yeah, make sure you commit all changes in `dist/` as well. Also, it looks like this isn't passing linting (the change should be simple enough though).

**Comment by addaleax** [comment]
Running `gulp` changed a lot more than I’d expect from my src/ change… I guess I have some newer version of some dependency installed, likely because it’s a fresh clone. Let me know if you’d like anything else changed here. :)

**Comment by nfischer** [comment]
@addaleax Thanks! I'll test this out on LInux.

**Comment by dthree** [comment]
Looks good @addaleax, thanks!

**Pull request merged**
